### ISSUE TITLE
Missing images in 01-admin slides

### ISSUE THREAD

**Issue by schoenja** [unibas-sweng/software-engineering#7]
There are images missing from the `images` folder for the presentation.

The affected lines are [Line 49](https://github.com/unibas-sweng/software-engineering/blob/master/docs/slides/01-admin.html#L49) and [Line 58](https://github.com/unibas-sweng/software-engineering/blob/master/docs/slides/01-admin.html#L58).

I did not add the images itself via a pull request due to the question whether the individual licensing of the images, especially the drill seargent, is not fully known.

**Comment by marcelluethi** [comment]
Thanks for pointing this out. This has happened because initially I did not intent to upload this presentation to github. I only uploaded it to Github due to the projector problems. But now that it is there, it should be complete. I will add the images to the repository.

If the google search tools can be trusted, all of the images that I used are licensed under CCA (and labeled free for reuse). Unfortunately I could not find a good way to find the correct attribution using google. This is why most of the images that I use are from wikipedia - where the necessary attribution is always given together with the images.
